### ISSUE TITLE
회원가입 시 중복되는 아이디 이슈

### ISSUE THREAD

**Issue by Charlezz** [hanyugyung/simple-board#1]
sign-up 호출 시 이미 존재하는 아이디라면 400 에러코드가 내려오고 있습니다.
에러코드 변경 또는 "이미 가입된 아이디 입니다" 식의 에러 메시지를 내려주시면 좋을 것 같습니다.

**Comment by hanyugyung** [comment]
```
{
  "result": "SUCCESS",
  "data": null,
  "errorCode": "90100",
  "errorMessage": "이미 존재하는 계정입니다."
}
```

위의 예시처럼 비즈니스 상 발생하는 비정상처리에 대한 예외를 처리할 수 있도록 상세 코드를 추가하였습니다.
모든 상세 errorCode 에 대해 스웨거 작성이 힘든 점이 있기 때문에 추후에 ReadMe 에 추가 기재하도록 하겠습니다!
