### ISSUE TITLE
[문의] 스웨거 응답 

### ISSUE THREAD

**Issue by Charlezz** [hanyugyung/simple-board#2]
<img width="1317" alt="스크린샷 2024-01-10 오전 11 17 03" src="https://github.com/hanyugyung/simple-board/assets/12824365/238b88ca-32cf-4267-b153-29b0713248ce">

스웨거에서 응답 예시 값이 동일합니다.
API 찔러서 내려오는 값으로 타입을 유추는 할 수 있긴한데요.
그래도 응답 예시가 있으면 수강생들이 편하게 확인할 수 있을 것 같습니다.

**Comment by hanyugyung** [comment]
리드미에 상세 에러코드를 작성하는 것으로 대체하겠습니다!
